# Implementing Deep Learning Models with Pytorch

## Introduction to Pytorch


Pytorch is described as:


A Python-based scientific computing package targeted at two sets of audiences:

1. A replacement for NumPy to use the power of GPUs
2. A deep learning research platform that provides maximum flexibility and speed



In [1]:
#!pip install torch

In [2]:
import torch

## Tensors

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[4.4585e+37, 7.8473e-43, 4.4585e+37],
        [7.8473e-43, 4.4583e+37, 7.8473e-43],
        [4.4583e+37, 7.8473e-43, 4.4576e+37],
        [7.8473e-43, 4.4576e+37, 7.8473e-43],
        [4.4584e+37, 7.8473e-43, 4.4584e+37]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1068, 0.5528, 0.0329],
        [0.2356, 0.6730, 0.0036],
        [0.9358, 0.8869, 0.4611],
        [0.7775, 0.5929, 0.9500],
        [0.4475, 0.5339, 0.9976]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
print(x.size())

torch.Size([2])


In [8]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [9]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [10]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [11]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!